### ISSUE TITLE
rsync-auto doesn't recongnize folders outside cwd

### ISSUE THREAD

**Issue by davidscotson** [AVADOLearning/moodle-ubiquitous#9]
I was seeing messages like this:

```
Davids-MacBook-Pro:moodle-ubiquitous davidscotson$ vagrant rsync-auto app-debug-1
==> app-debug-1: Not syncing /Users/davidscotson/github/moodle as it is not part of the current working directory.
```

It did work at one point. Possibly I moved the old directory that was working out the way, and moved a new directory into the same place.

It started working again. Not 100% sure why, possibly because I renamed the folder to Moodle with a capital M, possibly just by halting and upping the VM.

This issue seems similar, but I think I've got the fix they mention, as I'm on version 2.0.1 of Vagrant.

https://github.com/hashicorp/vagrant/issues/8770

**Comment by LukeCarrier** [comment]
I'm going to go ahead and close this issue as I've been unable to verify this. I believe it's still possible for this to fail if using symbolic links, but this isn't a configuration anyone's currently using. We also anticipate moving to Docker Compose and bind mounts for development in the near future for performance reasons, so I'm wary of investing too much time in Vagrant-specific changes.

Sorry we didn't get to this sooner.
